DOMAIN3 = [
    dict(
        num=12, topic=3,
        title="Automate Deployment with ARM Templates and Bicep",
        objective="Automate deployment of resources by using ARM templates or Bicep files",
        desc="Read, edit, and deploy resources with ARM templates and Bicep, then export and decompile between the two formats.",
        build="A storage account deployed from both an ARM template and a Bicep file.",
        services="ARM, Bicep, az deployment, Azure Storage, Cloud Shell",
        steps=[
            ("Create the resource group", "az group create --name rg-az104-lab12 --location eastus"),
            ("Interpret an ARM template's parameters/resources/outputs", ""),
            ("Modify the ARM template to add SKU and harden TLS", ""),
            ("Deploy the ARM template to the resource group", "az deployment group create --resource-group rg-az104-lab12 --template-file storage.json --parameters storageAccountName=$SANAME skuName=Standard_LRS"),
            ("Author and edit a Bicep file", ""),
            ("Compile the Bicep file to ARM JSON", "az bicep build --file storage.bicep"),
            ("Deploy the Bicep file", "az deployment group create --resource-group rg-az104-lab12 --template-file storage.bicep --parameters storageAccountName=$SANAME2 skuName=Standard_ZRS"),
            ("Export the deployment as an ARM template", "az group export --name rg-az104-lab12 > exported-rg.json"),
            ("Decompile the ARM template to Bicep", "az bicep decompile --file exported-rg.json"),
        ],
        test="Confirm both storage accounts exist and the exported template decompiles to Bicep.",
    ),
    dict(
        num=13, topic=3,
        title="Create a Virtual Machine, Encryption at Host, and Moving VMs",
        objective="Create and configure virtual machines",
        desc="Deploy a Linux VM with encryption at host enabled, then move it across resource groups, subscriptions, and regions.",
        build="A Linux VM with host-based encryption, moved between resource groups and regions.",
        services="Azure Virtual Machines, Managed Disks, Azure Resource Mover, ARM",
        steps=[
            ("Create source and destination resource groups", "az group create --name rg-az104-lab13 --location eastus"),
            ("Register the encryption-at-host feature", "az feature register --namespace Microsoft.Compute --name EncryptionAtHost"),
            ("Create a VM with encryption at host", "az vm create --resource-group rg-az104-lab13 --name vm-lab13 --image Ubuntu2204 --size Standard_B1s --admin-username azureuser --generate-ssh-keys --encryption-at-host --public-ip-sku Standard"),
            ("Verify encryption at host on the VM", "az vm show -g rg-az104-lab13 -n vm-lab13 --query securityProfile.encryptionAtHost"),
            ("Move the VM to another resource group", "az resource move --destination-group rg-az104-lab13-dest --ids $VMID"),
            ("Move the VM to another subscription", "az resource move --destination-group rg-az104-lab13-dest --destination-subscription-id $TARGET_SUB --ids $VMID"),
            ("Move the VM to another region with Resource Mover", "az resource-mover move-collection create --name mc-lab13 --resource-group rg-az104-lab13 --source-region eastus --target-region westus2 --location eastus2euap --identity type=SystemAssigned"),
        ],
        test="Confirm encryptionAtHost is true and the VM appears in the destination resource group.",
    ),
    dict(
        num=14, topic=3,
        title="VM Sizes, Disks, and Availability (Zones & Sets)",
        objective="Manage virtual machines",
        desc="Resize a VM, attach and expand a managed data disk, and deploy VMs into an availability zone and an availability set.",
        build="A resized VM with an expanded data disk plus zonal and availability-set VMs.",
        services="Azure Virtual Machines, Managed Disks, Availability Zones, Availability Sets",
        steps=[
            ("Create the resource group and a base VM", "az vm create --resource-group rg-az104-lab14 --name vm-lab14 --image Ubuntu2204 --size Standard_B1s --admin-username azureuser --generate-ssh-keys --public-ip-sku Standard"),
            ("List available and resizable VM sizes", "az vm list-vm-resize-options --resource-group rg-az104-lab14 --name vm-lab14 --output table"),
            ("Resize the VM", "az vm resize --resource-group rg-az104-lab14 --name vm-lab14 --size Standard_B2s"),
            ("Create and attach a managed data disk", "az vm disk attach --resource-group rg-az104-lab14 --vm-name vm-lab14 --name datadisk-lab14"),
            ("Expand the data disk", "az disk update --resource-group rg-az104-lab14 --name datadisk-lab14 --size-gb 64"),
            ("Deploy a VM into an availability zone", "az vm create --resource-group rg-az104-lab14 --name vm-zone1 --image Ubuntu2204 --size Standard_B1s --zone 1 --admin-username azureuser --generate-ssh-keys --public-ip-sku Standard"),
            ("Create an availability set", "az vm availability-set create --resource-group rg-az104-lab14 --name avset-lab14 --platform-fault-domain-count 2 --platform-update-domain-count 5"),
            ("Deploy VMs into the availability set", "az vm create -g rg-az104-lab14 -n vm-set-1 --availability-set avset-lab14 --image Ubuntu2204 --size Standard_B1s --admin-username azureuser --generate-ssh-keys"),
        ],
        test="Confirm the resized VM, the 64 GiB disk, the zonal VM, and both availability-set VMs exist.",
    ),
    dict(
        num=15, topic=3,
        title="Deploy and Configure a Virtual Machine Scale Set (VMSS) with Autoscale",
        objective="Deploy and configure a Virtual Machine Scale Set",
        desc="Create a VMSS behind a load balancer and attach autoscale rules that add and remove instances based on CPU usage.",
        build="A Flexible VMSS with CPU-based scale-out and scale-in autoscale rules.",
        services="Azure Virtual Machine Scale Sets, Azure Load Balancer, Azure Monitor Autoscale",
        steps=[
            ("Create the resource group", "az group create --name rg-az104-lab15 --location eastus"),
            ("Create the scale set behind a load balancer", "az vmss create --resource-group rg-az104-lab15 --name vmss-lab15 --orchestration-mode Flexible --image Ubuntu2204 --vm-sku Standard_B1s --instance-count 2 --admin-username azureuser --generate-ssh-keys --load-balancer vmss-lb --upgrade-policy-mode automatic"),
            ("View and manually scale instances", "az vmss scale --resource-group rg-az104-lab15 --name vmss-lab15 --new-capacity 3"),
            ("Create an autoscale profile with min/max/default", "az monitor autoscale create --resource-group rg-az104-lab15 --resource vmss-lab15 --resource-type Microsoft.Compute/virtualMachineScaleSets --name autoscale-lab15 --min-count 2 --max-count 10 --count 2"),
            ("Add a scale-out rule when CPU is high", "az monitor autoscale rule create --resource-group rg-az104-lab15 --autoscale-name autoscale-lab15 --condition \"Percentage CPU > 70 avg 5m\" --scale out 1"),
            ("Add a scale-in rule when CPU is low", "az monitor autoscale rule create --resource-group rg-az104-lab15 --autoscale-name autoscale-lab15 --condition \"Percentage CPU < 30 avg 5m\" --scale in 1"),
            ("Review the autoscale configuration", "az monitor autoscale rule list --resource-group rg-az104-lab15 --autoscale-name autoscale-lab15 --output table"),
            ("Update the instance SKU and roll to instances", "az vmss update --resource-group rg-az104-lab15 --name vmss-lab15 --set sku.name=Standard_B2s"),
        ],
        test="Confirm both scale rules and the min/max bounds appear in the autoscale settings.",
    ),
    dict(
        num=16, topic=3,
        title="Containers: ACR, Container Instances, and Container Apps",
        objective="Create and configure containers",
        desc="Build and push an image to Azure Container Registry, run it in Container Instances, then deploy and scale it in Container Apps.",
        build="An image in ACR running in both Container Instances and a scalable Container App.",
        services="Azure Container Registry, Azure Container Instances, Azure Container Apps, Log Analytics",
        steps=[
            ("Create the resource group", "az group create --name rg-az104-lab16 --location eastus"),
            ("Create an Azure Container Registry", "az acr create --resource-group rg-az104-lab16 --name $ACR --sku Basic --admin-enabled true"),
            ("Build and push an image with ACR Tasks", "az acr build --registry $ACR --image webapp:v1 https://github.com/Azure-Samples/acr-build-helloworld-node.git"),
            ("Provision a container with Container Instances", "az container create --resource-group rg-az104-lab16 --name aci-lab16 --image $ACR_SERVER/webapp:v1 --registry-login-server $ACR_SERVER --registry-username $ACR_USER --registry-password $ACR_PASS --dns-name-label acilab16$RANDOM --ports 80 --cpu 1 --memory 1.5"),
            ("Create a Container Apps environment", "az containerapp env create --name aca-env-lab16 --resource-group rg-az104-lab16 --location eastus"),
            ("Provision a container with Container Apps", "az containerapp create --name aca-lab16 --resource-group rg-az104-lab16 --environment aca-env-lab16 --image $ACR_SERVER/webapp:v1 --registry-server $ACR_SERVER --registry-username $ACR_USER --registry-password $ACR_PASS --target-port 80 --ingress external --cpu 0.5 --memory 1.0Gi"),
            ("Manage Container App sizing and scaling", "az containerapp update --name aca-lab16 --resource-group rg-az104-lab16 --min-replicas 0 --max-replicas 5 --scale-rule-name http-rule --scale-rule-type http --scale-rule-http-concurrency 50"),
            ("Manage registry images and usage", "az acr repository delete --name $ACR --image webapp:v1 --yes"),
        ],
        test="Browse the ACI and Container App FQDNs and confirm the web app responds.",
    ),
    dict(
        num=17, topic=3,
        title="Azure App Service: Plans, Scaling, TLS, Custom Domains, Backup, Networking, Slots",
        objective="Create and configure Azure App Service",
        desc="Create an App Service plan and web app, then configure scaling, TLS, custom domains, backup, networking, and deployment slots.",
        build="A Standard-tier web app with autoscale, TLS, backup, VNet integration, and a staging slot.",
        services="Azure App Service, App Service plans, Azure Monitor Autoscale, Managed Certificates, VNet integration",
        steps=[
            ("Create the resource group", "az group create --name rg-az104-lab17 --location eastus"),
            ("Provision a Standard App Service plan", "az appservice plan create --resource-group rg-az104-lab17 --name plan-lab17 --sku S1 --is-linux"),
            ("Create an App Service web app", "az webapp create --resource-group rg-az104-lab17 --plan plan-lab17 --name $APP --runtime \"NODE:20-lts\""),
            ("Configure scale up, scale out, and autoscale", "az monitor autoscale create -g rg-az104-lab17 --resource $PLANID --name autoscale-lab17 --min-count 1 --max-count 5 --count 1"),
            ("Map a custom DNS name", "az webapp config hostname add --resource-group rg-az104-lab17 --webapp-name $APP --hostname www.contoso.com"),
            ("Create and bind a managed TLS certificate", "az webapp config ssl bind --resource-group rg-az104-lab17 --name $APP --certificate-thumbprint $THUMB --ssl-type SNI"),
            ("Configure scheduled backups to storage", "az webapp config backup update --resource-group rg-az104-lab17 --webapp-name $APP --container-url \"$CONTAINER_URL\" --frequency 1d --retain-one true --retention 30"),
            ("Configure VNet integration and access restrictions", "az webapp vnet-integration add -g rg-az104-lab17 -n $APP --vnet vnet-lab17 --subnet appsvc-subnet"),
            ("Create a deployment slot and swap", "az webapp deployment slot swap --resource-group rg-az104-lab17 --name $APP --slot staging --target-slot production"),
        ],
        test="Confirm the app serves over HTTPS with TLS 1.2 and the staging slot swaps into production.",
    ),
]
