DOMAIN2 = [
    dict(
        num=7,
        topic=2,
        title="Create and Configure Storage Accounts and Redundancy",
        objective="Configure access to storage",
        desc="The learner creates general-purpose v2 storage accounts, switches redundancy tiers, configures encryption, and sets up object replication across accounts.",
        build="A source and destination storage account with an object replication policy.",
        services="Azure Storage, Blob storage, Azure Key Vault, object replication, az storage account",
        steps=[
            ("Create a resource group", "az group create --name rg-az104-lab07 --location eastus"),
            ("Create an LRS storage account", "az storage account create --name $SRC --resource-group rg-az104-lab07 --location eastus --sku Standard_LRS --kind StorageV2 --access-tier Hot"),
            ("Change redundancy to RA-GRS", "az storage account update --name $SRC --resource-group rg-az104-lab07 --sku Standard_RAGRS"),
            ("Inspect and set customer-managed key encryption", "az storage account update --name $SRC --resource-group rg-az104-lab07 --encryption-key-source Microsoft.Keyvault --encryption-key-vault \"https://$KV.vault.azure.net/\" --encryption-key-name storagecmk"),
            ("Create a destination account for replication", "az storage account create --name $DST --resource-group rg-az104-lab07 --location westus --sku Standard_LRS --kind StorageV2"),
            ("Enable versioning and change feed on both", "az storage account blob-service-properties update --account-name $ACC --resource-group rg-az104-lab07 --enable-versioning true --enable-change-feed true"),
            ("Create containers and upload a blob", "az storage blob upload --account-name $SRC --container-name orders --name sample.txt --file sample.txt --auth-mode login"),
            ("Configure an object replication policy", "az storage account or-policy create --account-name $DST --resource-group rg-az104-lab07 --source-account $SRC --destination-account $DST --source-container orders --destination-container orders --min-creation-time '2024-01-01T00:00:00Z'"),
        ],
        test="List blobs on the destination account and confirm the source blob has replicated asynchronously.",
    ),
    dict(
        num=8,
        topic=2,
        title="Configure Access to Storage: Firewalls, SAS, Access Keys",
        objective="Configure access to storage",
        desc="The learner rotates access keys, generates account and service SAS tokens, binds a SAS to a stored access policy, locks the account behind a firewall, and grants RBAC data access.",
        build="A firewalled storage account secured with SAS tokens, stored access policies, and RBAC roles.",
        services="Azure Storage, storage firewall + virtual networks, SAS, stored access policies, access keys, Azure RBAC",
        steps=[
            ("Create the resource group and storage account", "az storage account create --name $SA --resource-group rg-az104-lab08 --location eastus --sku Standard_LRS --kind StorageV2"),
            ("Create a container and upload a blob", "az storage blob upload --account-name $SA --container-name docs --name report.txt --file report.txt --auth-mode login"),
            ("List and rotate access keys", "az storage account keys renew --account-name $SA --resource-group rg-az104-lab08 --key primary"),
            ("Generate an account SAS", "az storage account generate-sas --account-name $SA --account-key $KEY --services b --resource-types sco --permissions rl --expiry $EXPIRY --https-only -o tsv"),
            ("Generate a service SAS for one blob", "az storage blob generate-sas --account-name $SA --account-key $KEY --container-name docs --name report.txt --permissions r --expiry $EXPIRY --https-only --full-uri -o tsv"),
            ("Create a stored access policy and bind a SAS", "az storage container policy create --account-name $SA --account-key $KEY --container-name docs --name readonly --permissions rl --expiry $POLICYEXP"),
            ("Configure the storage firewall and VNet rules", "az storage account update --name $SA --resource-group rg-az104-lab08 --default-action Deny --bypass AzureServices"),
            ("Grant identity-based RBAC access", "az role assignment create --assignee $USER --role \"Storage Blob Data Contributor\" --scope $SCOPE"),
        ],
        test="List blobs with --auth-mode login using only your RBAC identity, with no key or SAS supplied.",
    ),
    dict(
        num=9,
        topic=2,
        title="Configure Azure Blob Storage: Tiers, Lifecycle, Versioning",
        objective="Configure Azure Blob Storage",
        desc="The learner creates a blob container, moves blobs between hot/cool/cold/archive tiers, enables versioning and soft delete, and authors a JSON lifecycle management policy.",
        build="A blob container with tiered blobs, soft delete, versioning, and an automated lifecycle policy.",
        services="Azure Blob Storage, access tiers, blob/container soft delete, blob versioning, lifecycle management",
        steps=[
            ("Create the resource group and storage account", "az storage account create --name $SA --resource-group rg-az104-lab09 --location eastus --sku Standard_LRS --kind StorageV2 --access-tier Hot"),
            ("Create a blob container", "az storage container create --account-name $SA --name media --auth-mode login"),
            ("Upload blobs into different tiers", "az storage blob upload --account-name $SA --container-name media --name hot.txt --file hot.txt --tier Hot --auth-mode login"),
            ("Change the access tier of a blob", "az storage blob set-tier --account-name $SA --container-name media --name hot.txt --tier Archive --auth-mode login"),
            ("Enable blob versioning", "az storage account blob-service-properties update --account-name $SA --resource-group rg-az104-lab09 --enable-versioning true"),
            ("Enable soft delete for blobs and containers", "az storage account blob-service-properties update --account-name $SA --resource-group rg-az104-lab09 --enable-delete-retention true --delete-retention-days 7"),
            ("Author a JSON lifecycle management policy", "az storage account management-policy create --account-name $SA --resource-group rg-az104-lab09 --policy @policy.json"),
            ("Verify the lifecycle policy", "az storage account management-policy show --account-name $SA --resource-group rg-az104-lab09 -o json"),
        ],
        test="Show the management policy and confirm the tier-down and expire rules match the JSON you applied.",
    ),
    dict(
        num=10,
        topic=2,
        title="Configure Azure Files and Identity-Based Access",
        objective="Configure Azure Files",
        desc="The learner creates an SMB file share, uploads files, takes and restores snapshots, enables share soft delete, and configures identity-based authentication with share-level RBAC.",
        build="An SMB file share with snapshots, soft delete, and identity-based access.",
        services="Azure Files, share snapshots, file-share soft delete, identity-based authentication, Azure RBAC share roles",
        steps=[
            ("Create the resource group and storage account", "az storage account create --name $SA --resource-group rg-az104-lab10 --location eastus --sku Standard_LRS --kind StorageV2"),
            ("Create a file share with a quota", "az storage share-rm create --resource-group rg-az104-lab10 --storage-account $SA --name projects --quota 100 --access-tier TransactionOptimized"),
            ("Upload a file and list the share", "az storage file upload --account-name $SA --account-key $KEY --share-name projects --source plan.txt"),
            ("Enable share soft delete", "az storage account file-service-properties update --account-name $SA --resource-group rg-az104-lab10 --enable-delete-retention true --delete-retention-days 7"),
            ("Take a share snapshot", "az storage share snapshot --account-name $SA --account-key $KEY --name projects --query snapshot -o tsv"),
            ("Restore a file from a snapshot", "az storage file copy start --account-name $SA --account-key $KEY --source-share projects --source-path plan.txt --source-snapshot \"$SNAP\" --destination-share projects --destination-path plan-restored.txt"),
            ("Configure identity-based authentication", "az storage account update --name $SA --resource-group rg-az104-lab10 --enable-files-aadds true"),
            ("Assign a share-level RBAC role", "az role assignment create --assignee $USER --role \"Storage File Data SMB Share Contributor\" --scope \"$SHARESCOPE\""),
        ],
        test="List files inside the snapshot and confirm the restored file appears back in the live share.",
    ),
    dict(
        num=11,
        topic=2,
        title="Manage Data with Storage Explorer and AzCopy",
        objective="Configure Azure Blob Storage / Configure access to storage",
        desc="The learner provisions an account with two containers, then moves data with Azure Storage Explorer, AzCopy via SAS, and AzCopy via Entra login including a server-side copy.",
        build="A storage account with data transferred via Storage Explorer and AzCopy.",
        services="Azure Storage (Blob), Azure Storage Explorer, AzCopy, SAS, Azure RBAC",
        steps=[
            ("Create the account and two containers", "az storage container create --account-name $SA --name source --auth-mode login"),
            ("Grant yourself data-plane RBAC", "az role assignment create --assignee $USER --role \"Storage Blob Data Contributor\" --scope $SCOPE"),
            ("Install and connect Azure Storage Explorer", ""),
            ("Upload and download with the GUI", ""),
            ("Create test data and a container SAS", "az storage container generate-sas --account-name $SA --account-key $KEY --name source --permissions racwdl --expiry $EXPIRY --https-only -o tsv"),
            ("Upload a folder with AzCopy using a SAS", "azcopy copy \"$HOME/azcopydemo/*\" \"https://$SA.blob.core.windows.net/source?$SAS\" --recursive=true"),
            ("Copy account-to-account server-side", "azcopy copy \"https://$SA.blob.core.windows.net/source?$SAS\" \"https://$SA.blob.core.windows.net/backup?$BACKUPSAS\" --recursive=true"),
            ("Use AzCopy with Entra login and sync", "azcopy sync \"$HOME/azcopydemo\" \"https://$SA.blob.core.windows.net/source\" --recursive=true"),
        ],
        test="Run azcopy list on the source container URL and confirm the uploaded and synced files are present.",
    ),
]
