DOMAIN5 = [
    dict(
        num=23, topic=5,
        title="Azure Monitor: Metrics, Logs, KQL, and Alerts",
        objective="Monitor resources with Azure Monitor",
        desc="Build the full Azure Monitor loop: a Log Analytics workspace, diagnostic settings, metrics, KQL queries, and alerts.",
        build="A Log Analytics workspace with diagnostic data, KQL queries, and metric/activity/processing alert rules.",
        services="Azure Monitor, Log Analytics workspace, Metrics, Alerts, Action Groups, Alert Processing Rules, VM Insights",
        steps=[
            ("Create resource group and Log Analytics workspace", "az monitor log-analytics workspace create --resource-group \"$RG\" --workspace-name \"$WS\" --location \"$LOCATION\" --retention-time 30"),
            ("Deploy a monitored VM and storage account", "az vm create --resource-group \"$RG\" --name \"vm-az104-lab23\" --image Ubuntu2204 --size Standard_B1s --admin-username azureuser --generate-ssh-keys --public-ip-sku Standard"),
            ("Read platform metrics such as Percentage CPU", "az monitor metrics list --resource \"$VM_ID\" --metric \"Percentage CPU\" --aggregation Average --interval PT5M"),
            ("Route logs via diagnostic settings to the workspace", "az monitor diagnostic-settings create --name \"diag-to-law\" --resource \"$STORAGE_ID/blobServices/default\" --workspace \"$WS_ID\" --logs '[{\"category\":\"StorageRead\",\"enabled\":true}]' --metrics '[{\"category\":\"Transaction\",\"enabled\":true}]'"),
            ("Enable VM Insights (Azure Monitor Agent + DCR)", "az vm extension set --resource-group \"$RG\" --vm-name \"vm-az104-lab23\" --name AzureMonitorLinuxAgent --publisher Microsoft.Azure.Monitor --enable-auto-upgrade true"),
            ("Query logs with KQL against Heartbeat/Perf/AzureActivity", "az monitor log-analytics query --workspace \"$WS_GUID\" --analytics-query \"Heartbeat | summarize LastHeartbeat = max(TimeGenerated) by Computer\" --output table"),
            ("Create an action group for notifications", "az monitor action-group create --resource-group \"$RG\" --name \"ag-az104-lab23\" --short-name \"az104ag\" --action email admin angch@tertiaryinfotech.com"),
            ("Create a metric alert on high CPU", "az monitor metrics alert create --name \"alert-vm-highcpu\" --resource-group \"$RG\" --scopes \"$VM_ID\" --condition \"avg Percentage CPU > 80\" --window-size 5m --evaluation-frequency 1m --severity 3 --action \"$AG_ID\""),
            ("Create an alert processing rule across the RG", "az monitor alert-processing-rule create --name \"apr-add-ag\" --resource-group \"$RG\" --scopes \"/subscriptions/$SUB_ID/resourceGroups/$RG\" --rule-type AddActionGroups --action-groups \"$AG_ID\""),
        ],
        test="In Monitor → Logs the KQL queries return data and the metric/activity/processing alert rules appear under Monitor → Alerts.",
    ),
    dict(
        num=24, topic=5,
        title="Azure Network Watcher and Connection Monitor",
        objective="Monitor networks with Azure Network Watcher",
        desc="Use Network Watcher's diagnostic tools to verify traffic rules, trace routing, capture packets, and continuously monitor reachability between VMs.",
        build="Two VMs diagnosed with IP flow verify, next hop, NSG flow logs, packet capture, and a Connection Monitor.",
        services="Azure Network Watcher, IP Flow Verify, Next Hop, NSG Diagnostics, Packet Capture, Connection Monitor, VNet, NSG, VMs",
        steps=[
            ("Create resource group and virtual network", "az network vnet create --resource-group \"$RG\" --name \"vnet-az104-lab24\" --address-prefix 10.10.0.0/16 --subnet-name \"subnet-app\" --subnet-prefix 10.10.1.0/24"),
            ("Deploy two VMs with an NSG allowing SSH/HTTP", "az vm create -g \"$RG\" -n \"vm-web\" --image Ubuntu2204 --size Standard_B1s --vnet-name \"vnet-az104-lab24\" --subnet \"subnet-app\" --admin-username azureuser --generate-ssh-keys --public-ip-sku Standard --nsg \"nsg-web\""),
            ("Run IP flow verify to check a 5-tuple", "az network watcher test-ip-flow --vm \"$VMWEB_ID\" --direction Inbound --protocol TCP --local \"10.10.1.4:80\" --remote \"13.68.0.1:50000\""),
            ("Trace routing with next hop", "az network watcher show-next-hop --resource-group \"$RG\" --vm \"vm-web\" --source-ip 10.10.1.4 --dest-ip 8.8.8.8"),
            ("View effective NSG rules on the NIC", "az network nic list-effective-nsg --ids \"$NIC_ID\" -o jsonc"),
            ("Enable NSG flow logs to a storage account", "az network watcher flow-log create --location \"$LOCATION\" --name \"flowlog-nsg-web\" --nsg \"$NSG_ID\" --storage-account \"$STORAGE_ID\" --retention 7 --enabled true"),
            ("Capture packets on the VM for offline analysis", "az network watcher packet-capture create --resource-group \"$RG\" --vm \"vm-web\" --name \"pcap-vm-web\" --storage-account \"$STORAGE\" --time-limit 60"),
            ("Run a point-in-time connection troubleshoot", "az network watcher test-connectivity --resource-group \"$RG\" --source-resource \"vm-web\" --dest-address \"$VMAPP_IP\" --dest-port 22"),
            ("Configure a continuous Connection Monitor", "az network watcher connection-monitor create --name \"cm-web-to-app\" --location \"$LOCATION\" --endpoint-source-name \"src-vm-web\" --endpoint-source-resource-id \"$VMWEB_ID\" --endpoint-dest-name \"dst-vm-app\" --endpoint-dest-address \"$VMAPP_IP\" --test-config-name \"tcp-22\" --protocol Tcp --tcp-port 22 --frequency 30"),
        ],
        test="IP flow verify returns Allow/Deny with the deciding rule, and Connection Monitor shows ongoing reachability results between vm-web and vm-app.",
    ),
    dict(
        num=25, topic=5,
        title="Azure Backup: Recovery Services Vault, Policies, Backup and Restore",
        objective="Implement backup and recovery",
        desc="Create a Recovery Services vault, author a custom backup policy, protect a VM, run backups, and perform file-level and full VM restores.",
        build="A Recovery Services vault protecting a VM with a custom policy, recovery points, and configured backup reports/alerts.",
        services="Recovery Services vault, Azure Backup, Backup policy, Virtual Machine, Backup center / Backup reports, Azure Monitor alerts",
        steps=[
            ("Create resource group and Recovery Services vault", "az backup vault create --resource-group \"$RG\" --name \"$VAULT\" --location \"$LOCATION\""),
            ("Set backup storage redundancy to GRS", "az backup vault backup-properties set --resource-group \"$RG\" --name \"$VAULT\" --backup-storage-redundancy GeoRedundant"),
            ("Deploy a VM to protect", "az vm create --resource-group \"$RG\" --name \"vm-az104-lab25\" --image Ubuntu2204 --size Standard_B1s --admin-username azureuser --generate-ssh-keys --public-ip-sku Standard"),
            ("Create a custom daily backup policy", "az backup policy create --resource-group \"$RG\" --vault-name \"$VAULT\" --name \"pol-daily-30d\" --backup-management-type AzureIaasVM --policy @policy.json"),
            ("Enable backup protection on the VM", "az backup protection enable-for-vm --resource-group \"$RG\" --vault-name \"$VAULT\" --vm \"vm-az104-lab25\" --policy-name \"pol-daily-30d\""),
            ("Run an on-demand backup", "az backup protection backup-now --resource-group \"$RG\" --vault-name \"$VAULT\" --container-name \"vm-az104-lab25\" --item-name \"vm-az104-lab25\" --backup-management-type AzureIaasVM --retain-until 31-07-2026"),
            ("Restore individual files via ILR mount", "az backup restore files mount-rp --resource-group \"$RG\" --vault-name \"$VAULT\" --container-name \"vm-az104-lab25\" --item-name \"vm-az104-lab25\" --rp-name \"$RP\""),
            ("Restore the full VM disks to staging", "az backup restore restore-disks --resource-group \"$RG\" --vault-name \"$VAULT\" --container-name \"vm-az104-lab25\" --item-name \"vm-az104-lab25\" --rp-name \"$RP\" --storage-account \"$STORAGE\" --target-resource-group \"$RG\""),
            ("Configure vault diagnostics for backup reports/alerts", "az monitor diagnostic-settings create --name \"vault-diag\" --resource \"$VAULT_ID\" --workspace \"$WS_ID\" --logs '[{\"category\":\"CoreAzureBackup\",\"enabled\":true},{\"category\":\"AddonAzureBackupJobs\",\"enabled\":true}]'"),
        ],
        test="az backup item list shows the VM protected with recovery points, and the restore jobs complete successfully in Backup Jobs.",
    ),
    dict(
        num=26, topic=5,
        title="Azure Site Recovery: Replicate, Fail Over, and Interpret Health",
        objective="Implement disaster recovery",
        desc="Enable Azure-to-Azure replication for a VM, run test and real failovers with re-protect and failback, and interpret replication health.",
        build="A VM replicated to a secondary region via ASR with test/real failover, failback, and a Recovery Plan.",
        services="Recovery Services vault (Site Recovery), Azure Site Recovery (Azure-to-Azure), source VM, source/target VNets, cache storage account",
        steps=[
            ("Create resource group, source VM, and vault", "az backup vault create --resource-group \"$RG\" --name \"$VAULT\" --location \"$PRIMARY\""),
            ("Pre-create DR resource group, VNet, and cache storage", "az network vnet create --resource-group \"rg-az104-lab26-dr\" --name \"vnet-dr\" --location \"$SECONDARY\" --address-prefix 10.20.0.0/16 --subnet-name \"default\" --subnet-prefix 10.20.1.0/24"),
            ("Enable Site Recovery replication for the VM", ""),
            ("Adjust the replication policy (snapshot frequency/retention)", ""),
            ("Interpret replication health, status, and RPO", "az resource list --resource-group \"$RG\" --resource-type \"Microsoft.RecoveryServices/vaults\" -o table"),
            ("Run a non-disruptive test failover into an isolated VNet", ""),
            ("Perform a failover to the secondary region and commit", "az vm list --resource-group \"rg-az104-lab26-dr\" -o table"),
            ("Re-protect and fail back to the primary region", ""),
            ("Build a Recovery Plan for orchestrated failover", ""),
        ],
        test="The replicated item reaches Protected/Healthy with a current RPO, and a test failover creates a working VM in the secondary region.",
    ),
]
