DOMAIN1 = [
    dict(
        num=1,
        topic=1,
        title="Manage Microsoft Entra Users and Groups",
        objective="Manage Microsoft Entra users and groups",
        desc="The learner creates cloud users, builds security and Microsoft 365 groups, manages membership and properties, and assigns licenses in Microsoft Entra ID.",
        build="A team of Entra users, a security group, a Microsoft 365 group, and a dynamic group",
        services="Microsoft Entra ID, az ad, Microsoft Graph, licenses",
        steps=[
            ("Sign in and confirm your tenant primary domain", 'DOMAIN=$(az rest --method get --url "https://graph.microsoft.com/v1.0/domains?\\$select=id,isDefault" --query "value[?isDefault].id" -o tsv)'),
            ("Create individual cloud users", 'az ad user create --display-name "Jane Doe" --user-principal-name "jdoe@$DOMAIN" --password "P@ssw0rd-Lab1!" --force-change-password-next-sign-in true'),
            ("Edit user job title, department and usage location", 'az ad user update --id "jdoe@$DOMAIN" --set jobTitle="Cloud Administrator" department="IT" usageLocation="SG"'),
            ("Bulk create users from a list (Portal bulk create)", 'az ad user create --display-name "Amy Tan" --user-principal-name "atan@$DOMAIN" --password "P@ssw0rd-Lab1!" --force-change-password-next-sign-in true'),
            ("Create a security group and a Microsoft 365 group", 'az ad group create --display-name "grp-az104-admins" --mail-nickname "grp-az104-admins"'),
            ("Add users as members and verify membership", 'az ad group member add --group "$GROUP_ID" --member-id "$JANE_ID"'),
            ("Create a dynamic-membership group driven by department", 'az rest --method post --url "https://graph.microsoft.com/v1.0/groups" --headers "Content-Type=application/json" --body \'{"displayName":"grp-az104-it-dynamic","mailNickname":"grp-az104-it-dynamic","mailEnabled":false,"securityEnabled":true,"groupTypes":["DynamicMembership"],"membershipRule":"(user.department -eq \\"IT\\")","membershipRuleProcessingState":"On"}\''),
            ("Inspect tenant SKUs and assign a license to a user", 'az rest --method post --url "https://graph.microsoft.com/v1.0/users/jdoe@$DOMAIN/assignLicense" --headers "Content-Type=application/json" --body \'{ "addLicenses": [ { "skuId": "<SKU_ID>", "disabledPlans": [] } ], "removeLicenses": [] }\''),
        ],
        test="Verify the users appear in All users, the groups list their members, the dynamic rule auto-adds IT users, and the assigned license shows on the user.",
    ),
    dict(
        num=2,
        topic=1,
        title="Manage External (B2B Guest) Users and Configure SSPR",
        objective="Manage external users and self-service password reset",
        desc="The learner invites a B2B guest user, reviews external collaboration and cross-tenant settings, then enables and scopes self-service password reset with authentication methods and registration.",
        build="A redeemed B2B guest user, a partners group, and a scoped SSPR configuration",
        services="Microsoft Entra ID, External Identities / B2B, Password reset (SSPR), az rest",
        steps=[
            ("Sign in and set the tenant primary-domain variable", 'DOMAIN=$(az rest --method get --url "https://graph.microsoft.com/v1.0/domains?\\$select=id,isDefault" --query "value[?isDefault].id" -o tsv)'),
            ("Invite a B2B guest user by email", 'az rest --method post --url "https://graph.microsoft.com/v1.0/invitations" --headers "Content-Type=application/json" --body \'{ "invitedUserEmailAddress": "partner.test@gmail.com", "invitedUserDisplayName": "Contoso Partner", "inviteRedirectUrl": "https://myapps.microsoft.com", "sendInvitationMessage": true }\''),
            ("Verify the guest and add it to a partners group", 'az ad group member add --group "$GRP_ID" --member-id "$GUEST_ID"'),
            ("Review External collaboration settings and authorization policy", 'az rest --method get --url "https://graph.microsoft.com/v1.0/policies/authorizationPolicy" --query "{allowInvitesFrom:allowInvitesFrom, guestUserRole:guestUserRoleId}"'),
            ("Review Cross-tenant access (B2B) default settings", ""),
            ("Enable and scope SSPR to a selected group (Portal)", ""),
            ("Configure SSPR authentication methods, registration and notifications (Portal)", ""),
            ("Test the reset flow; contrast SSPR with an admin reset", 'az ad user update --id "jdoe@$DOMAIN" --password "N3wP@ssw0rd-Lab2!" --force-change-password-next-sign-in true'),
        ],
        test="Verify the guest shows User type = Guest with an #EXT# UPN, and a scoped test user can register methods and reset their password via https://aka.ms/sspr.",
    ),
    dict(
        num=3,
        topic=1,
        title="Manage Access to Azure Resources with RBAC",
        objective="Manage access to Azure resources",
        desc="The learner assigns built-in Azure roles at subscription, resource-group and resource scopes, interprets effective access with Check access, then builds and assigns a custom role.",
        build="Role assignments at three scopes plus a custom 'VM Restart Operator' role",
        services="Azure RBAC (role assignments, role definitions), Resource Manager, Storage account",
        steps=[
            ("Set variables and create a target resource group", 'az group create --name "rg-az104-lab03" --location "southeastasia"'),
            ("Create a storage account to act as a scoped resource", 'az storage account create --name "$SA" --resource-group "$RG" --location "$LOCATION" --sku Standard_LRS'),
            ("Explore built-in role definitions (Owner/Contributor/Reader)", 'az role definition list --name "Contributor" --query "[0].permissions[0].{actions:actions, notActions:notActions}"'),
            ("Assign Reader to a group at subscription scope", 'az role assignment create --assignee-object-id "$GRP_ID" --assignee-principal-type Group --role "Reader" --scope "/subscriptions/$SUB_ID"'),
            ("Assign Contributor at resource-group scope", 'az role assignment create --assignee-object-id "$JANE_ID" --assignee-principal-type User --role "Contributor" --scope "/subscriptions/$SUB_ID/resourceGroups/$RG"'),
            ("Assign Storage Blob Data Reader at resource scope", 'az role assignment create --assignee-object-id "$RAJ_ID" --assignee-principal-type User --role "Storage Blob Data Reader" --scope "$SA_ID"'),
            ("Interpret effective access including inherited assignments", 'az role assignment list --scope "$SA_ID" --include-inherited -o table'),
            ("Create and assign a minimal custom role", "az role definition create --role-definition /tmp/vm-restart-role.json"),
        ],
        test="Use Check access and 'az role assignment list --include-inherited' to confirm each principal has the expected role at the right scope, and that the custom role is assignable.",
    ),
    dict(
        num=4,
        topic=1,
        title="Implement and Manage Azure Policy",
        objective="Implement and manage Azure Policy",
        desc="The learner assigns a built-in policy, authors a custom definition, bundles policies into an initiative, reads compliance, and remediates non-compliant resources with a managed identity.",
        build="An Allowed-locations assignment, a custom tag policy, a governance initiative, and a remediation task",
        services="Azure Policy (definitions, initiatives, assignments, remediation), managed identity, Storage accounts",
        steps=[
            ("Create a resource group as the policy scope", 'az group create --name "rg-az104-lab04" --location "southeastasia"'),
            ("Assign the built-in Allowed locations policy", 'az policy assignment create --name "allowed-locations-lab04" --policy "$LOC_DEF" --scope "$SCOPE" --params \'{ "listOfAllowedLocations": { "value": [ "southeastasia" ] } }\''),
            ("Test the Deny effect against a disallowed region", 'az storage account create --name "stlab04deny$RANDOM" --resource-group "$RG" --location "eastus" --sku Standard_LRS'),
            ("Author a custom policy definition requiring a tag", 'az policy definition create --name "require-env-tag-on-storage" --display-name "Storage accounts must have an Environment tag" --mode Indexed --rules /tmp/require-env-tag.json --subscription "$SUB_ID"'),
            ("Create an initiative (policy set) and assign it", 'az policy set-definition create --name "az104-governance-baseline" --display-name "AZ-104 Governance Baseline" --definitions /tmp/initiative.json --subscription "$SUB_ID"'),
            ("Trigger a scan and interpret compliance state", 'az policy state list --resource-group "$RG" --query "[].{resource:resourceId, state:complianceState, policy:policyDefinitionName}" -o table'),
            ("Assign a Modify policy with managed identity and remediate", 'az policy remediation create --name "remediate-env-tag" --resource-group "$RG" --policy-assignment "$ASSIGN_ID"'),
            ("Add an exemption to waive a specific resource", 'az policy exemption create --name "exempt-legacy-sa" --policy-assignment "$ASSIGN_ID" --exemption-category Waiver --scope "$SA_ID" --description "Legacy account exempt from Environment tag until migrated"'),
        ],
        test="Confirm the Deny effect blocks the disallowed region, the Compliance blade shows compliant/non-compliant counts, and the remediation task tags existing resources.",
    ),
    dict(
        num=5,
        topic=1,
        title="Manage Resource Groups, Locks and Tags",
        objective="Manage resource groups and subscriptions",
        desc="The learner creates resource groups, deploys a resource, applies and updates tags, moves the resource between groups, and protects resources with CanNotDelete and ReadOnly locks.",
        build="Two resource groups, a tagged storage account moved to an archive RG, and delete/read-only locks",
        services="Azure Resource Manager (resource groups, tags, resource locks, resource move), Storage account",
        steps=[
            ("Create two resource groups", 'az group create --name "rg-az104-lab05" --location "southeastasia"'),
            ("Deploy a storage account to tag, move and lock", 'az storage account create --name "$SA" --resource-group "$RG" --location "$LOCATION" --sku Standard_LRS'),
            ("Apply tags to the resource group", 'az tag create --resource-id "/subscriptions/$(az account show --query id -o tsv)/resourceGroups/$RG" --tags CostCenter=1001 Environment=Dev Owner=angch'),
            ("Merge, update and delete tags on the resource", 'az tag update --resource-id "$SA_ID" --operation Merge --tags Environment=Dev Project=AZ104'),
            ("Move the resource to the archive resource group", 'az resource move --destination-group "$RG2" --ids "$SA_ID"'),
            ("Apply a CanNotDelete lock on the archive RG", 'az lock create --name "lock-no-delete" --lock-type CanNotDelete --resource-group "$RG2" --notes "Protect archived resources from deletion"'),
            ("Test the lock, then apply a ReadOnly lock on the resource", 'az lock create --name "lock-readonly" --lock-type ReadOnly --resource-group "$RG2" --resource-name "$SA" --resource-type "Microsoft.Storage/storageAccounts" --namespace "Microsoft.Storage"'),
            ("Manage subscription-level resource providers", 'az provider register --namespace "Microsoft.Storage"'),
        ],
        test="Verify the tags read back correctly, the resource now lives in the archive RG, and a delete attempt fails with a ScopeLocked error while the locks are in place.",
    ),
    dict(
        num=6,
        topic=1,
        title="Manage Costs and Configure Management Groups",
        objective="Manage subscriptions and governance",
        desc="The learner analyzes costs, creates a budget with alert thresholds, reviews Azure Advisor cost recommendations, and builds a management-group hierarchy to apply governance at scale.",
        build="A monthly budget with alerts, an action group, and an mg-az104 management-group hierarchy",
        services="Microsoft Cost Management (Cost analysis, budgets, alerts), Azure Advisor, Management groups",
        steps=[
            ("Set subscription and tenant variables", 'SUB_ID=$(az account show --query id -o tsv)'),
            ("Analyze month-to-date cost by service", 'az costmanagement query --type ActualCost --scope "/subscriptions/$SUB_ID" --timeframe MonthToDate --dataset-aggregation \'{ "totalCost": { "name": "Cost", "function": "Sum" } }\' --dataset-grouping name="ServiceName" type="Dimension" -o table'),
            ("Create an action group for budget alert emails", 'az monitor action-group create --name "ag-budget-alerts" --resource-group "$RG_MON" --short-name "budgetAG" --action email admin angch@tertiaryinfotech.com'),
            ("Create a monthly budget with alert thresholds", 'az consumption budget create --budget-name "budget-az104-monthly" --amount 100 --category Cost --time-grain Monthly --start-date "2026-07-01" --end-date "2027-06-30" --notifications \'{ "warning80": { "enabled": true, "operator": "GreaterThanOrEqualTo", "threshold": 80, "contactEmails": ["angch@tertiaryinfotech.com"] } }\''),
            ("Review fired cost / anomaly alerts", 'az rest --method get --url "https://management.azure.com/subscriptions/$SUB_ID/providers/Microsoft.CostManagement/alerts?api-version=2023-08-01" --query "value[].{name:name, type:properties.definition.type, status:properties.status}" -o table'),
            ("Review Azure Advisor cost recommendations", 'az advisor recommendation list --query "[?category==\'Cost\'].{impact:impact, problem:shortDescription.problem, resource:resourceMetadata.resourceId}" -o table'),
            ("Create a management-group hierarchy", 'az account management-group create --name "mg-az104-prod" --display-name "AZ104 Prod" --parent "mg-az104-root"'),
            ("Move the subscription and assign inherited governance", 'az account management-group subscription add --name "mg-az104-nonprod" --subscription "$SUB_ID"'),
        ],
        test="Confirm the budget and action group appear with the configured thresholds, Advisor lists cost recommendations, and the subscription sits under the management-group hierarchy with the role inherited downward.",
    ),
]
