DOMAIN4 = [
    dict(
        num=18, topic=4,
        title="Virtual Networks, Subnets & VNet Peering",
        objective="Configure virtual networks",
        desc="Create two virtual networks with non-overlapping address spaces and subnets, then peer them so resources communicate over the Azure backbone without a VPN or public IPs.",
        build="Two peered VNets (hub and spoke) in Connected state.",
        services="Virtual Network, Subnets, VNet Peering, Network Watcher, az network vnet",
        steps=[
            ("Create the resource group", "az group create --name rg-az104-lab18 --location eastus"),
            ("Create first VNet vnet-hub with a subnet", "az network vnet create --resource-group rg-az104-lab18 --name vnet-hub --address-prefixes 10.10.0.0/16 --subnet-name snet-hub-app --subnet-prefixes 10.10.1.0/24 --location eastus"),
            ("Create second VNet vnet-spoke with a subnet", "az network vnet create --resource-group rg-az104-lab18 --name vnet-spoke --address-prefixes 10.20.0.0/16 --subnet-name snet-spoke-app --subnet-prefixes 10.20.1.0/24 --location eastus"),
            ("Add a second subnet to the hub VNet", "az network vnet subnet create --resource-group rg-az104-lab18 --vnet-name vnet-hub --name snet-hub-mgmt --address-prefixes 10.10.2.0/24"),
            ("Create the peering from hub to spoke", "az network vnet peering create --resource-group rg-az104-lab18 --name hub-to-spoke --vnet-name vnet-hub --remote-vnet vnet-spoke --allow-vnet-access"),
            ("Create the reverse peering from spoke to hub", "az network vnet peering create --resource-group rg-az104-lab18 --name spoke-to-hub --vnet-name vnet-spoke --remote-vnet vnet-hub --allow-vnet-access"),
            ("Verify the peering state is Connected", "az network vnet peering show --resource-group rg-az104-lab18 --vnet-name vnet-hub --name hub-to-spoke --query \"{name:name, state:peeringState}\" -o table"),
            ("Deploy test VMs and check connectivity", "az network watcher test-connectivity --resource-group rg-az104-lab18 --source-resource vm-hub --dest-resource vm-spoke --dest-port 22"),
        ],
        test="Both peerings show peeringState = Connected and test-connectivity across the peering returns Reachable.",
    ),
    dict(
        num=19, topic=4,
        title="Public IPs, User-Defined Routes & Connectivity Troubleshooting",
        objective="Configure IP addressing and routing",
        desc="Allocate a static Standard public IP, build a route table with a user-defined route forcing traffic through a virtual appliance, associate it to a subnet, then troubleshoot the resulting effective routes.",
        build="A route table with a 0.0.0.0/0 UDR associated to a workload subnet.",
        services="Public IP address, Route Table (UDR), Virtual Network, Network Watcher, NIC, az network route-table",
        steps=[
            ("Create the resource group and a VNet", "az network vnet create --resource-group rg-az104-lab19 --name vnet-lab19 --address-prefixes 10.30.0.0/16 --subnet-name snet-workload --subnet-prefixes 10.30.1.0/24"),
            ("Create a static Standard SKU public IP", "az network public-ip create --resource-group rg-az104-lab19 --name pip-web-static --sku Standard --allocation-method Static --version IPv4"),
            ("Inspect the allocated address", "az network public-ip show --resource-group rg-az104-lab19 --name pip-web-static --query \"{ip:ipAddress, sku:sku.name}\" -o table"),
            ("Create a route table", "az network route-table create --resource-group rg-az104-lab19 --name rt-workload --location eastus"),
            ("Add a UDR to a virtual appliance", "az network route-table route create --resource-group rg-az104-lab19 --route-table-name rt-workload --name route-to-nva --address-prefix 0.0.0.0/0 --next-hop-type VirtualAppliance --next-hop-ip-address 10.30.1.4"),
            ("Associate the route table to the subnet", "az network vnet subnet update --resource-group rg-az104-lab19 --vnet-name vnet-lab19 --name snet-workload --route-table rt-workload"),
            ("Deploy a test VM with the static public IP", "az vm create --resource-group rg-az104-lab19 --name vm-web --image Ubuntu2204 --size Standard_B1s --vnet-name vnet-lab19 --subnet snet-workload --public-ip-address pip-web-static --admin-username azureuser --generate-ssh-keys"),
            ("View the effective routes on the NIC", "az network nic show-effective-route-table --resource-group rg-az104-lab19 --name \"$NIC\" -o table"),
            ("Troubleshoot connectivity with Network Watcher", "az network watcher test-connectivity --resource-group rg-az104-lab19 --source-resource vm-web --dest-address 13.107.42.14 --dest-port 443"),
        ],
        test="The NIC effective routes show a User-source 0.0.0.0/0 route to VirtualAppliance, and test-connectivity returns Unreachable confirming the UDR diverts traffic.",
    ),
    dict(
        num=20, topic=4,
        title="Network Security Groups, Application Security Groups & Effective Rules",
        objective="Secure network traffic",
        desc="Create an NSG with prioritized custom rules, group VMs by role using application security groups, reference those ASGs in NSG rules, then read the effective security rules Azure computes for a NIC.",
        build="An NSG with ASG-based allow/deny rules associated to a subnet.",
        services="Network Security Group, Application Security Group, Virtual Network, NIC, Network Watcher, az network nsg",
        steps=[
            ("Create the resource group, VNet and subnet", "az network vnet create --resource-group rg-az104-lab20 --name vnet-lab20 --address-prefixes 10.40.0.0/16 --subnet-name snet-app --subnet-prefixes 10.40.1.0/24"),
            ("Create application security groups", "az network asg create --resource-group rg-az104-lab20 --name asg-web --location eastus"),
            ("Create the network security group", "az network nsg create --resource-group rg-az104-lab20 --name nsg-app --location eastus"),
            ("Allow HTTPS from internet to the web ASG", "az network nsg rule create --resource-group rg-az104-lab20 --nsg-name nsg-app --name Allow-HTTPS-Web --priority 100 --direction Inbound --access Allow --protocol Tcp --source-address-prefixes Internet --destination-asgs asg-web --destination-port-ranges 443"),
            ("Allow SQL only from web ASG to db ASG", "az network nsg rule create --resource-group rg-az104-lab20 --nsg-name nsg-app --name Allow-SQL-Web-to-DB --priority 110 --direction Inbound --access Allow --protocol Tcp --source-asgs asg-web --destination-asgs asg-db --destination-port-ranges 1433"),
            ("Explicitly deny everything else inbound", "az network nsg rule create --resource-group rg-az104-lab20 --nsg-name nsg-app --name Deny-All-Inbound --priority 4000 --direction Inbound --access Deny --protocol '*' --source-address-prefixes '*' --destination-address-prefixes '*' --destination-port-ranges '*'"),
            ("Associate the NSG to the subnet", "az network vnet subnet update --resource-group rg-az104-lab20 --vnet-name vnet-lab20 --name snet-app --network-security-group nsg-app"),
            ("Deploy VMs and place NICs in the ASGs", "az network nic ip-config update -g rg-az104-lab20 --nic-name \"$WEB_NIC\" -n ipconfig1 --application-security-groups asg-web"),
            ("Evaluate the effective security rules", "az network nic list-effective-nsg --resource-group rg-az104-lab20 --name \"$WEB_NIC\" -o table"),
        ],
        test="IP flow verify on vm-web returns Allow by Allow-HTTPS-Web for port 443 and Deny for port 22.",
    ),
    dict(
        num=21, topic=4,
        title="Azure Bastion, Service Endpoints & Private Endpoints",
        objective="Provide secure access to PaaS and VMs",
        desc="Deploy Azure Bastion for browser-based RDP/SSH without VM public IPs, lock a storage account to a subnet with a service endpoint, then bring that storage into the VNet with a private endpoint and private DNS.",
        build="Azure Bastion plus a storage account reachable via a private endpoint.",
        services="Azure Bastion, Virtual Network, Public IP, Service Endpoints, Private Endpoint, Private DNS Zone, Azure Storage",
        steps=[
            ("Create the resource group and VNet", "az network vnet create --resource-group rg-az104-lab21 --name vnet-lab21 --address-prefixes 10.50.0.0/16 --subnet-name snet-workload --subnet-prefixes 10.50.1.0/24"),
            ("Add the AzureBastionSubnet (/26 or larger)", "az network vnet subnet create --resource-group rg-az104-lab21 --vnet-name vnet-lab21 --name AzureBastionSubnet --address-prefixes 10.50.2.0/26"),
            ("Create a Standard public IP for Bastion", "az network public-ip create --resource-group rg-az104-lab21 --name pip-bastion --sku Standard --allocation-method Static"),
            ("Deploy Azure Bastion", "az network bastion create --resource-group rg-az104-lab21 --name bastion-lab21 --vnet-name vnet-lab21 --public-ip-address pip-bastion --location eastus --sku Standard"),
            ("Deploy a VM with no public IP for Bastion", "az vm create --resource-group rg-az104-lab21 --name vm-jump --image Ubuntu2204 --size Standard_B1s --vnet-name vnet-lab21 --subnet snet-workload --public-ip-address \"\" --admin-username azureuser --generate-ssh-keys"),
            ("Create a storage account for endpoint tests", "az storage account create --resource-group rg-az104-lab21 --name $STG --sku Standard_LRS --kind StorageV2 --location eastus"),
            ("Enable a service endpoint on the subnet", "az network vnet subnet update --resource-group rg-az104-lab21 --vnet-name vnet-lab21 --name snet-workload --service-endpoints Microsoft.Storage"),
            ("Restrict the storage account to that subnet", "az storage account network-rule add --resource-group rg-az104-lab21 --account-name $STG --vnet-name vnet-lab21 --subnet snet-workload"),
            ("Create a private endpoint and integrate DNS", "az network private-endpoint create --resource-group rg-az104-lab21 --name pe-storage-blob --vnet-name vnet-lab21 --subnet snet-workload --private-connection-resource-id \"$STG_ID\" --group-id blob --connection-name pe-storage-conn"),
        ],
        test="From vm-jump via Bastion, nslookup of the storage blob endpoint resolves to a 10.50.x.x private IP instead of a public address.",
    ),
    dict(
        num=22, topic=4,
        title="Azure DNS & Load Balancing",
        objective="Configure name resolution and load balancing",
        desc="Host a public DNS zone with A and CNAME records, then build a public Standard load balancer with a backend pool, health probe and rule across two VMs, and troubleshoot uneven traffic distribution.",
        build="A public DNS zone plus a Standard load balancer distributing across two VMs.",
        services="Azure DNS, Azure Load Balancer (Standard), Public IP, Virtual Network, Backend Pool, Health Probe, Network Watcher",
        steps=[
            ("Create the resource group and VNet", "az network vnet create --resource-group rg-az104-lab22 --name vnet-lab22 --address-prefixes 10.60.0.0/16 --subnet-name snet-backend --subnet-prefixes 10.60.1.0/24"),
            ("Create a public Azure DNS zone", "az network dns zone create --resource-group rg-az104-lab22 --name contoso-az104-demo.com"),
            ("Add A and CNAME records to the zone", "az network dns record-set a add-record --resource-group rg-az104-lab22 --zone-name contoso-az104-demo.com --record-set-name www --ipv4-address 20.1.2.3"),
            ("Create a Standard public IP for the LB", "az network public-ip create --resource-group rg-az104-lab22 --name pip-lb --sku Standard --allocation-method Static"),
            ("Create the public load balancer with frontend", "az network lb create --resource-group rg-az104-lab22 --name lb-web --sku Standard --public-ip-address pip-lb --frontend-ip-name fe-web --backend-pool-name pool-web"),
            ("Add a health probe", "az network lb probe create --resource-group rg-az104-lab22 --lb-name lb-web --name probe-http --protocol Tcp --port 80 --interval 5"),
            ("Add a load-balancing rule", "az network lb rule create --resource-group rg-az104-lab22 --lb-name lb-web --name rule-http --protocol Tcp --frontend-port 80 --backend-port 80 --frontend-ip-name fe-web --backend-pool-name pool-web --probe-name probe-http"),
            ("Deploy two backend VMs into the pool", "az network nic ip-config address-pool add --resource-group rg-az104-lab22 --nic-name \"$NIC\" --ip-config-name ipconfig1 --lb-name lb-web --address-pool pool-web"),
            ("Test and troubleshoot load balancing", "az monitor metrics list --resource $(az network lb show -g rg-az104-lab22 -n lb-web --query id -o tsv) --metric DipAvailability VipAvailability -o table"),
        ],
        test="Browsing the LB frontend IP repeatedly alternates responses between vm-web1 and vm-web2, confirming traffic distribution.",
    ),
]
